Interaction
gisachris/To-Do-List pull request #5
Opened 2023-05-12 11:16 UTC by gisachris

## IN This PR I present the To-Do-List app Interactions :
Below are some of my implementations as well as going over the project requirements 🤝 .
## Requirements
-Add a new JavaScript file and import it as a module 📜 
-the script should contain methods related to the status updates (`completed`: `true` / `false`). 🎉 
-Add event listener to the checkbox (`change`). 🥇 
-Update items object's value for the `completed` key upon user actions. 🟡 
-Implement a function for the "Clear all completed" button (use` filter()` method). 🔎 
-Store the updated array of items in local storage 🔒 

## Achievements
-Create a new JavaScript file for the new Interactions.✅
-add the necessary logic 🧠 to add and remove items to the list and to the Dom  📜 ✅
-By default, new tasks should have the property `completed` set to `false` and the `index` set to the value of the arraylength✅
-Add event listener to the checkbox (`change`). 🥇 
-Update items object's value for the `completed` key upon user actions. 🟡
-Deleting a task should update all remaining items' `indexes`.✅
-All changes to the To Do List should be saved in local storage.✅
-add styling 🎨  based on the list structure given ✅

## Conclusion
**I would love to hear 👂  from you my CR in terms of what can be better implemented 👨‍💻  for the site thankyou!. And I look forward to hearing from you soon.**  🙇

2023-05-12 12:39 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @gisachris , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/xNJPkAQnLGVGjYpsBW/giphy.gif"/>

## Highlights


## Required Changes ♻️
- [ ] Good job so far @gisachris You have done a great job so far. There are just a few changes you need to make and you'll be on your way to the next project 😉 
- [ ] To begin with, from the video below, you can see that whenever the checkbox is ticked and the item is marked as completed and the page is refreshed, the item goes back to how it was before. However per the project requirements, the updated array of items needs to be stored in local storage, so the user gets the correct list of values after the page reloads (which means that any changes made to the list should be preserved 😉 So kindly fix this as well 👍 
- [ ] Also, from the video below you can see that whenever a new list is added the entire page refreshes but this behaviour isn't ideal for users. So I will advice that in order to improve user interactivity, you fix this behaviour of your app. 💯 
- Video Reference
Uploading Screen Recording 2023-05-12 at 12.15.15 PM.mov…



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 13:07 UTC, gisachris commented
hello @NahnahAJ thank you for the review 🙇 I am grateful. I have one question about the `complete key values`.
I wrote a script that specifically requested for the user to click the delete button for  `complete key values` to stay `true` and get deleted.

Then added an edge case so that when the user refreshed the page and the `delete button` was never clicked to return the `completed key value`  back to `false`. So my question is :

-for example when a user checks the `checkbox` and refreshes should the list item be removed the same way its done when the `delete button` is clicked..? thank you!

2023-05-12 13:38 UTC, NahnahAJ commented
Hello @gisachris To answer your question no the item shouldn’t be removed since it has only been ticked as completed and hasn’t been deleted. Instead it needs to be saved in the local storage so that when the page is refreshed it’ll still be checked as completed unless the user changes it back to not completed. I hope this answers your question 😊

2023-05-13 03:52 UTC, gisachris commented
## After my previous Code-Review i was asked to make some changes ♻️  on the To-Do-List app Interactions :
Below are some of my implementations as well as going over the Review requirements 🤝 .
## Requirements
-when the page is refreshed the completed object key should retain its value if `true` stay `true` if `false` stay `false`.
-when a new task is added the page is refreshed which is a bad user experience. so remove reloading when an item Is added 

## Achievements
-when the page is refreshed the completed object key retains its value if `true` stay `true` if `false` stay `false`..✅
-Remove reloading when a new task Is added.✅

## Conclusion
**I would love to hear 👂  from you my CR in terms of what can be better implemented 👨‍💻  for the site thankyou!. And I look forward to hearing from you soon.**  🙇

2023-05-13 04:56 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

### Hey @gisachris 👋

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following Requirements

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 04:56 UTC, HAMMAS-SALEEM commented on src/modules/addRemove.js
>  });
**[OPTIONAL]**

- [ ] It would be nice if you make your commit message capitalized to make your pull request more professional 👍

2023-05-13 10:25 UTC, merged